#!/bin/bash
/usr/bin/dtc -O dtb -o emu-00A0.dtbo -b 0 -@ emu-00A0.dts
cp emu-00A0.dtbo /lib/firmware
if [ -e /sys/devices/platform/bone_capemgr/slots ]
then
   CAPE=/sys/devices/platform/bone_capemgr/slots
else
   CAPE=/sys/devices/bone_capemgr.*/slots
   # Enable A/D
   echo cape-bone-iio > $CAPE
fi
echo emu:00A0 > $CAPE

# 2-5, 22,23,26,27 Drive select and head select
pins="2 3 4 5 22 23 26 27 8 9 10 11 46"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo in > /sys/class/gpio/gpio$pin/direction
done
# 30 track0, 31 drive1 select/recovery, 
# 60 emulation xcvr en
# 61 testing
pins="30 31 60 61"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo low > /sys/class/gpio/gpio$pin/direction
done
# 14,15 drive selected LEDS
# 50 mfm read xcvr en
pins="14 15 50"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo high > /sys/class/gpio/gpio$pin/direction
done
REV=`cat /sys/class/gpio/gpio46/value`
if [ $REV == '0' ]; then
   echo Rev B Board
else
   echo Rev A Board
fi

