#!/bin/bash
dtc -O dtb -o mfm_read-00A0.dtbo -b 0 -@ mfm_read-00A0.dts
cp mfm_read-00A0.dtbo /lib/firmware
if [ -e /sys/devices/platform/bone_capemgr/slots ]
then
   CAPE=/sys/devices/platform/bone_capemgr/slots
else
   CAPE=/sys/devices/bone_capemgr.*/slots
   # Enable A/D
   echo cape-bone-iio > $CAPE
fi
echo mfm_read:00A0 > $CAPE
# 2-5 rev A head, 8-11 rev B head, all high is head 0
# 44 emu second driver emulation, disable
# 60 MFM emulation tranceiver enable, high is disabled
pins="2 3 4 5 8 9 10 11 44 60"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo high > /sys/class/gpio/gpio$pin/direction
done
# Set inactive 22,23,26,27 Drive select, 110 write
# 50 read transceiver enable, low enabled
pins="22 23 26 27 110 50"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo low > /sys/class/gpio/gpio$pin/direction
done

# 30 track 0, 46 REVB pin
pins="30 46"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo in > /sys/class/gpio/gpio$pin/direction
done


REV=`cat /sys/class/gpio/gpio46/value`
if [ $REV == '0' ]; then
   echo Rev B Board
else
   echo Rev A Board
fi

